config/routes.rb
Ideaborough::Application.routes.draw do

resources :users
resources :sessions, :only => [:new, :create, :destroy]
resources :microposts do #, :only => [:create, :destroy, :show]
resources :comments #, :only => [:create, :destroy]
end
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/microposts',   :to => 'microposts#show'  

root :to => "pages#home"

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  attr_accessible :comment
  
  belongs_to :micropost
  
  validates :comment, :presence => true
  
  default_scope :order => 'comments.created_at ASC'
  
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base	

	attr_accessible :content, :coreidea
	 
	belongs_to :user
	has_many :comments, :dependent => :destroy
	
	validates :coreidea, :presence => true, :length => { :maximum => 50 }
	validates :content, :length => { :maximum => 200 }
	validates :user_id, :presence => true
	
	default_scope :order => 'microposts.created_at DESC'
	
	
end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
	attr_accessor :password
	attr_accessible :name, :email, :password, :password_confirmation
	has_many :microposts, :dependent => :destroy
	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :name, :presence => true,
			  :length   => { :maximum => 50 }
	validates :email, :presence => true,
		      :format   => { :with => email_regex },
			  :uniqueness => { :case_sensitive => false} 
	validates :password, :presence => true,
			  :confirmation => true,
			  :length => { :within => 5..40 }
			  
	before_save :encrypt_password

    def has_password?(submitted_password)
	 encrypted_password == encrypt(submitted_password)
	end
	def feed
	  Micropost.where("user_id = ?", id)
	end
	
	def self.authenticate(email, submitted_password)
     user = find_by_email(email) #implied User.find_by_email because self definition is inside User class
     return nil  if user.nil? #returns nil if user can't be found
     return user if user.has_password?(submitted_password) #returns user if password match, skips to end of sequence (returns nil) if password mismatch
    end
	
	def self.authenticate_with_salt(id, cookie_salt)
     user = find_by_id(id)
     (user && user.salt == cookie_salt) ? user : nil
    end
	
	private

    def secure_hash(string)
	  Digest::SHA2.hexdigest(string)
	end
	
	def make_salt
	  secure_hash("#{Time.now.utc}--#{password}")
	end
	
	def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end
	
	def encrypt_password
	  self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end
		
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 
 def create
 @micropost  = Micropost.find(params[:micropost_id])
 @comment  = @micropost.comments.create(params[:comment])
 if @comment.save
    redirect_to micropost_path(@micropost)
  else
    redirect_to micropost_path(@micropost)
  end
end
 
 def destroy
 end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
 
 before_filter :authorized_user, :only => :destroy

  def create
  @micropost  = current_user.microposts.build(params[:micropost])
    if @micropost.save
    #  flash[:success] = "Idea stored!"
      redirect_to root_path
    else
      @feed_items = []
	  render 'pages/home'
    end
  end

def show
@user = current_user
@micropost = @user.microposts.find(params[:id])
#@comments = @micropost.comments.new
end

def edit
 @micropost  = Micropost.find(params[:id])
end 
 
def destroy
 @micropost.destroy
 redirect_to root_path
 end
 
 private

    def authorized_user
      @micropost = Micropost.find(params[:id])
      redirect_to root_path unless current_user?(@micropost.user)
    end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
	@title = "Welcome"
    if signed_in?
	  @micropost = Micropost.new 
	  @feed_items = current_user.feed.paginate(:page => params[:page])
    end
  end

  def contact
    @title = "Contact"
  end
  
  def about
	@title = "About"
  end
  def help
	@title = "Support"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
	@title = "Sign in"
  end
  
  def create
    user = User.authenticate(params[:session][:email],
							 params[:session][:password])
	if user.nil?
	  flash.now[:error] = "Invalid email/password combination."
      @title = "Sign in"
      render 'new'	
	else
	  sign_in user
	  redirect_back_or root_path
	end
  end
  
  def destroy
    sign_out
	redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_filter :authenticate, :only => [:show]
before_filter :correct_user, :only => [:show]
  def show
    @user = User.find(params[:id])
	@title = @user.name
  end

  def new
    @user = User.new
    @title = "Sign up"
  end
  
  def create
  @user = User.new(params[:user])
   if @user.save #if this is possible, do it
	UserMailer.welcome_email(@user).deliver
	sign_in @user
    flash[:success] = "Welcome to Ideaborough."
	redirect_to root_path
   else
   @title = "Sign up"
   @user.password = ""
   @user.password_confirmation = ""
   render 'new'
   end
 end
   
   def edit
	 @user = User.find(params[:id])
	 @title = "Edit user"
   end
   
   def update
	  @user = User.find(params[:id])
	if @user.update_attributes(params[:user])
	  flash[:success] = "Profile updated."
	  redirect_to @user
	else
	  @title ="Edit user"
	  render 'edit'
	end
end

	def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(:page => params[:page])
    @title = @user.name
  end
  private
  def authenticate
    deny_access unless signed_in?
  end
def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
#Page specific titles -ST
	def title
		base_title = "Ideaborough"
			return base_title if @title.nil?
			return "#{base_title} | #{@title}"
	end
#Logo definition
	def logo
		image_tag("logo.png", :alt => "Ideaborough", :class => "round")	
	end
	def default
		image_tag("default.png", :alt => "Ideaborough", :class => "round")	
	end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    @current_user ||= user_from_remember_token
  end
  
  def current_user=(user)
    @current_user = user
  end
  
def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
	self.current_user = user
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def sign_out
    cookies.delete(:remember_token)
	self.current_user = nil
  end
  
  def current_user?(user)
    user == current_user
  end
  
  def deny_access
    store_location
	redirect_to signin_path, :notice => "Please sign in to access this page."
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end

  private

    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end

    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end
	
	def store_location
      session[:return_to] = request.fullpath
    end

    def clear_return_to
      session[:return_to] = nil
    end
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, options = {:size => 50})
	    gravatar_image_tag(user.email.downcase, :alt => user.name,
                                            :class => 'gravatar',
                                            :gravatar => options)
  end
end

app/views/layouts/_footer.html.erb
<footer>

  <nav class="round">
    <ul>
	  <li><%= link_to "About", about_path %></li>
	  <li><a href="http://www.drudgereport.com/">News</a></li>
	  <li><%= link_to "Support", help_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
  <br />
<div class="disclaimer">
All ideas are safe and secured to your account.<br />
&copy Ideaborough 2011.
</footer>

app/views/layouts/_header.html.erb
<header>
<%= link_to logo, root_path %>
	<nav class ="round">
		<ul>
			<li><%= link_to "Home", root_path %></li>
			<% if signed_in? %>
              <li><%= link_to "Profile", current_user %></li>
			<% end %>
			<li><%= link_to "About", about_path %></li>
					    <% if signed_in? %>
              <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
            <% else %>
			  <li><%= link_to "Sign in", signin_path %></li>
            <% end %>
		</ul>
	</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag 'screen', :media => 'screen' %>
    <%= stylesheet_link_tag 'print',  :media => 'print' %>	
	<!--[if lt IE 9]>
	<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
    <%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
	<meta name="google-site-verification" content="I0YkkeuVowhS-t2dtBlZgHNtDIGg8zfdfABs1Tuh610" />
    <%= csrf_meta_tag %>
	<%= render 'layouts/stylesheets' %>
	<%= javascript_include_tag :defaults %>
	<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-16833599-3']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
  </head>
  <body>
	<div class ="container">
	<%= render 'layouts/header' %>
			<section class="round">
				<% flash.each do |key, value| %>
					<div class="flash <%= key %>"><%= value %></div>
				<% end %>
				<%= yield %>
			</section>
	<%= render 'layouts/footer' %>
	<%= debug(params) if Rails.env.development? %>
	</div>
  </body>
</html>

app/views/microposts/_micropost.html.erb
<tr>
  <td class="micropost">
    <span class="content"><strong><%= simple_format(auto_link(micropost.coreidea)) %></strong></span><br />
	<span class="content"><%= simple_format(auto_link(micropost.content)) %></span>
    <span class="timestamp" align ="right">
      Conceived <%= time_ago_in_words(micropost.created_at) %> ago.
    </span>
  </td>
</tr>

app/views/microposts/show.html.erb
<h1>Idea #<%= SecureRandom.random_number(99999) %></h1><br/>
<p>
<strong><%= simple_format(auto_link(@micropost.coreidea)) %></strong>
</p>
<p>
<%= simple_format(auto_link(@micropost.content)) %>
</p>
<% @micropost.comments.each do |comment| %>
<p><ul>
<li><%= simple_format(auto_link(comment.comment)) %>
</ul>
</p>
<% end %>
<div>
<%= render 'shared/comment_form' %>
</div>

app/views/pages/about.html.erb
<h1>What is this place all about?</h1>

<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
<p>
I made this site because I got tired of losing track of my ideas. </p>
<p>
I tried sending myself e-mails, using To-Do apps and writing things down, but I could never keep track of anything for very long. 
</p>
<p>I hope that this place can help people like you and me solve the problem of lost ideas.</p>
<p>We're starting off fairly simply here, but if you stick around, I think this place could turn out to be pretty neat.</p>
<p>And whether you're here to stay, or are just stopping by, thanks for coming, and feel free to get in touch anytime by <a href="mailto:steve@ideaborough.com"><strong>clicking here.</strong></a>
</p>
    </td>
    <td>
     <div align="right"> <blockquote>
	Stop writing your ideas on napkins.<br/>It's ridiculous</blockquote><br />
	</div>
	</td>
  </tr>
</table>
 <%= link_to "Get started now.", signup_path, :class => "signup_button round" %>

app/views/pages/contact.html.erb
<h1>Welcome to Ideaborough</h1>
<p>
	Hi, my name is Steve. I guess you could say I am the mayor of Ideaborough. <br/>
	You can contact me by <a href="mailto:steve@ideaborough"><strong>clicking here.</strong></a>
</p>
  

app/views/pages/help.html.erb
<h1>Support</h1>
<table class="profile" summary="Profile information">
<tr>
 <td class="main">
   <p>
	Nothing formal.<br /> Nothing fancy. <br /><br />
	Just send me an e-mail if you have any questions and I'll get back
	to you really quickly. <br />I promise. <a href="mailto:steve@ideaborough.com"><strong>Click here.</strong></a>
   </p>
 </td>
<td>
     <div align="right"> <blockquote>

	</div>
	</td>
  </tr>
</table>
 <%= link_to "Get started now.", signup_path, :class => "signup_button round" %>

app/views/pages/home.html.erb
<% if signed_in? %>
  <table class="front" summary="For signed-in users">
    <tr>
      <td class="main">
        <h1>Any clever ideas?</h1>
        <%= render 'shared/micropost_form' %>
		
		<%= render 'shared/feed' %>
      </td>
      <td class="sidebar round">
        <%= render 'shared/user_info' %>
      </td>
    </tr>
  </table>
<% else %>

<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
<div class = "what">
	  <%= link_to "What is this place?", about_path %>
</div>
    </td>
    <td>
     <div align="right"> <blockquote>
	A place where your ideas can go to avoid being lost, buried or forgotten.</blockquote><br />
    <%= link_to "Get started now.", signup_path, :class => "signup_button round" %>
	</div>
	</td>
  </tr>
</table>

<% end %>

app/views/shared/_comment_form.html.erb
<div class = "fieldtitle">Additional thoughts (HTML is ok)</div>
<%= form_for([@micropost, @micropost.comments.build]) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
  <!--  <h4><%= pluralize(object.errors.count, "thing") %> 
        made it so that this <%= object.class.to_s.underscore.humanize.downcase %> couldn't be saved:</h4> -->
    <ul> <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% unless @feed_items.empty? %>
  <span class="ideassofar">Your ideas so far</span>
  <table class="microposts" summary="User microposts">
	<%= render :partial => 'shared/feed_item', :collection => @feed_items %>
  
  </table>
  
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<tr>
 <!--  <td class="gravatar">
    <%= link_to default, root_path %>
	<%= link_to gravatar_for(feed_item.user), feed_item.user %> 
  </td> -->
  <td class="micropost">
   <!-- <span class="user">
      <%= link_to feed_item.user.name, feed_item.user %> 
    </span> COMMENTED OUT BECAUSE DON'T NEED USERNAME AT THIS POINT -->
	<span class="coreidea"><strong><%= link_to feed_item.coreidea, feed_item %></strong></span><br />
	<span class="content"><%= simple_format(auto_link(feed_item.content)) %></span><br />
    <span class="timestamp" align = "right">
      Conceived <%= time_ago_in_words(feed_item.created_at) %> ago.
    </span>
  </td>
  <% if current_user?(feed_item.user) %>
  <td>
  <div class = "deleteexpand">
	<%= link_to "expand", feed_item %><br />
	<%= link_to "delete", feed_item, :method => :delete,
                                     :confirm => "Are you sure? You can never ever undo this.",
                                     :title => feed_item.content %>
</div>									 
  </td>
  <% end %>
</tr>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class = "fieldtitle">Core idea </div>
    <div class = "field">
      <%= f.text_field :coreidea %>
    </div>
  <div class = "fieldtitle">More info</div>
    <div class="field">
      <%= f.text_area :content %>
    </div>

  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/shared/_user_info.html.erb
<div class="user_info">
  <a href="<%= user_path(current_user) %>">
    <%= link_to default, root_path %>
<!--	<%= gravatar_for current_user, :size => 30 %> -->
    <span class="user_name">
      <%= current_user.name %><br/>
	  <%= pluralize(current_user.microposts.count, "idea") %>
    </span>
  </a>
</div>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= form_for(@user) do |f| %>
 <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, :autofocus => true %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<div>
  <%= gravatar_for @user %>
  <a href="http://gravatar.com/emails">Change your face</a>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
<%= render 'shared/error_messages', :object => f.object %>
<div class = "fieldtitle">Name</div>
  <div class="field">
    <%= f.text_field :name, :autofocus => true %>
  </div>
  <div class = "fieldtitle">E-mail</div>
  <div class="field">
    <%= f.text_field :email %>
  </div>
  <div class = "fieldtitle">Password</div>
  <div class="field">
    <%= f.password_field :password %>
  </div>
   <div class = "fieldtitle">Password (Again)</div>
  <div class="field">
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
      <h1>
        <%= link_to default, root_path %>
		<!-- <%= gravatar_for @user %> Until fully online -->
        <%= @user.name %>'s ideas.
      </h1>
	  <% unless @user.microposts.empty? %>
		<table class="microposts" summary="User microposts">
          <%= render @microposts %>
        </table>
        <%= will_paginate @microposts %>
      <% end %>
	</td>
    <td class="sidebar round">
	  <strong>Ideas:</strong> <%= @user.microposts.count %> <br />
	  <strong>URL</strong> <%= link_to user_path(@user), @user %><br />
      <strong><%= link_to "Edit Profile", edit_user_path(current_user) %></strong>
	</td>
  </tr>
</table>